### ISSUE TITLE
Unable to run t-SNE and Phenograph

### ISSUE THREAD

**Issue by IMCroswell** [BodenmillerGroup/histoCAT#101]
I failed to run t-SNE and Phenograph in Histocat 1.75 on my windows 10 computer.

![HistoCat issue](https://user-images.githubusercontent.com/81765931/139456101-5f378b0b-95d8-43e4-a7b0-d9ddd909cc38.png)

Thank you

**Comment by DenisSch** [comment]
@IMCroswell Thank you for reporting this issue.
Are you running histoCAT with admin rights?

**Comment by IMCroswell** [comment]
Yes, we did try with Admin rights.

**Comment by DenisSch** [comment]
@IMCroswell 
Could you run histoCAT via command line to see whether an error message is printed?
To run histoCAT in command line follow these steps:
https://www.wikihow.com/Run-Exe-from-Cmd-on-PC-or-Mac

**Comment by IMCroswell** [comment]
Doesn't seem to work

![image](https://user-images.githubusercontent.com/81765931/140184111-87886ac8-e6b4-419c-a5fc-f328454a7aba.png)

**Comment by DenisSch** [comment]
@IMCroswell Could you make sure whether this is there correct folder? It should include the ".exe". Please also make sure you have full administrative access.

**Comment by IMCroswell** [comment]
Thank you so much- DenisSch

It is working now.
