### ISSUE TITLE
Installation on M1 Mac Monterey

### ISSUE THREAD

**Issue by ollielomas** [BodenmillerGroup/histoCAT#102]
Hi

Installation consistently crashes when trying to install on an M1 MacBook running macOS Monterey. Any insights or tips to get it working?

Thanks 

Oliver

**Comment by jarcen21** [comment]
I am having the same issue with the new MacOS. Any help with the issue would be greatly appreciated.

**Comment by adoppeldy** [comment]
same issue... histocat++ works fine, but I did not find a manual, which makes it harder to use.

**Comment by adoppeldy** [comment]
after having a closer look at histocat++ the program still seems to be working fine, but I am not able to get the files to load properly. I always choose "add files" then they seem to appear in the app. I am able to rightklick on them and press "load", but nothing seems to happen... Any help out there?

**Comment by DenisSch** [comment]
Thank you for reporting this issue. I will response in more detail here: #104

**Comment by DenisSch** [comment]
Please see #104 for updates.
