### ISSUE TITLE
Histocat not loading files 

### ISSUE THREAD

**Issue by rachel662** [BodenmillerGroup/histoCAT#103]
Hi there
I have some images and a cell mask in a folder however when I try and load them into histocat it doesn't load anything 
Do you know why this might be? 

Thanks so much for your help 
Rachel

**Comment by rachel662** [comment]
Hey there
I've tried running histocat through matlab and i get this error when trying to load files - would anyone be able to give me any advice on how to fix it? 

cheers
Rachel 



Error in histoCAT (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('Master_LoadSamples',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

**Comment by DenisSch** [comment]
@rachel662 Does the [exemplar](https://github.com/BodenmillerGroup/histoCAT/releases/download/histoCAT_1.76/Example_Images.zip) data work for you without any issues?

If the exemplar images work well, would you be able to share an example image and mask from your side?

**Comment by DenisSch** [comment]
If this is still relevant, please open this issue.
