### ISSUE TITLE
Problem loading the histoCAT app

### ISSUE THREAD

**Issue by enwadozi** [BodenmillerGroup/histoCAT#105]
Hello,
I am relatively new to histoCAT (v 1.75) and have been using it without issue for the past month. Recently, when trying to load the software I get the following error: "C:\windows\system32>Undefined function or variable 'matlabrc'.". I have tried uninstalling/re-installing both histoCAT and MATLAB but this did not solve the problem.

I appreciate any help you are able to offer to resolve this issue.

Best,
Emmanuel

**Comment by DenisSch** [comment]
Feel free to post your solution so other people know how to solve it :)

**Comment by enwadozi** [comment]
Sure! Happy to do so.
I deleted the mcr cache file (C:\Users\[username]\AppData\Local\Temp\[username]\mcrCache[version]) which seemed to do the trick! The app works fine now.
