### ISSUE TITLE
phenograph: which visual studio components are needed?

### ISSUE THREAD

**Issue by E5ten** [BodenmillerGroup/histoCAT#112]
When I try to use the phenograph function, it does not progress. I think this might be because my visual studio installation does not have all that is needed by histocat. Which specific visual studio components do I need to have installed to use the phenograph?

**Comment by DenisSch** [comment]
This is a great question. Unfortunately, I have never received a response:
https://github.com/jacoblevine/PhenoGraph/issues/8
