### ISSUE TITLE
Histocat MacBook air download issue

### ISSUE THREAD

**Issue by histocat** [BodenmillerGroup/histoCAT#121]
I am currently having some difficulty downloading the Histocat software for Image Mass Cytometry data analysis on my MacBook Air. I repeatedly attempted to download the software from the Bodenmiller Group site but I am still running into some issues. What can I do to address this? Thanks!

**Comment by DenisSch** [comment]
Please download the newest version here: https://github.com/BodenmillerGroup/histoCAT/releases/download/histoCAT_1.761/histoCAT_1.761_MacOS15.app.zip

**Comment by histocat** [comment]
I keep receiving this message unfortunately. 
<img width="1425" alt="Screen Shot 2022-10-20 at 1 48 42 PM" src="https://user-images.githubusercontent.com/116280426/197021627-d4d6082c-53b3-460c-9552-56511b349dc4.png">

**Comment by DenisSch** [comment]
Please follow these steps:
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by DenisSch** [comment]
Please re-open if still an issue.
