### ISSUE TITLE
Sample Loading Issue

### ISSUE THREAD

**Issue by ellepoeta** [BodenmillerGroup/histoCAT#123]
Hi, 
I have run into a couple of problems when working with the desktop app of HistoCAT. I am trying to load files from MCD viewer with a Cell Profiler segmentation in Windows. 
First, when I select files to load as samples none of the ROIs or Markers show in the columns. I can select the files, set the pixels to 4, and select the do not transform option however there are no samples loading. I have tried closing out and restarting, uninstalling, and reinstalling the software, even going back to a previous version, with no luck. Today I went through and deleted all the files I have from the HistoCAT.exe thinking maybe the prior downloads may have caused issues. After doing this I downloaded a fresh version of the software and not am getting an error message and the software will not open at all. I also have a second computer I have tried, however it has only had the problem with the data files not loading into the program.

**Comment by DenisSch** [comment]
histoCAT requires a tiff files and a single cell mask for loading. Loading MCD files is not supported. Is this what you tried?

**Comment by DenisSch** [comment]
Example images: https://github.com/BodenmillerGroup/histoCAT/releases/download/histoCAT_1.76/Example_Images.zip

**Comment by ellepoeta** [comment]
Good Afternoon,
I used mcd view to turn my mcd files into tiffs for this. I was able to make a cell mask using Cell Profiler from these tiffs. When I load these tiff files with the cell mask nothing populates in the columns once inside HistoCAT. I have tried to load these files into the two most recent software versions.


Regards,
Elle Poeta
Research Asst. II
Ext: +87747
________________________________

**Comment by DenisSch** [comment]
Are you able to load the example images?

**Comment by ellepoeta** [comment]
I trained through  Standard Bio Tools. During the training, I was supplied with data and was able to load them. However, since then even these files that I know can be loaded, have also stopped loading. I just tried those sample files, and they are also not loading into the program.

Regards,
Elle Poeta
Research Asst. II
Ext: +87747
________________________________

**Comment by DenisSch** [comment]
Can you please check with these files:
https://github.com/BodenmillerGroup/histoCAT/releases/download/histoCAT_1.76/Example_Images.zip

**Comment by ellepoeta** [comment]
Yes, those were the file linked in the prior email. I did try these; however, I had the same issue.

Regards,
Elle Poeta
Research Asst. II
Ext: +87747
________________________________

**Comment by ellepoeta** [comment]
Hello,
I just got out of a meeting with a representative of Standard bio tools and was able to solve this issue. I had a mask of a different ROI saved out of Cell Profiler due to an error in that software. I apologize for my own oversight in this. Thank you for being so responsive and assisting with this.

Regards,
Elle Poeta
Research Asst. II
Ext: +87747
________________________________
