### ISSUE TITLE
question about coordinate spaces output from histoCAT

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/histoCAT#13]
Hello. this is more of a question.

 I am using histoCAT and am able to extract (X,Y) coordinates of a specific gate.  I am analyzing these point patterns locally in R to explore several hypotheses.  I am very interested in looking at the overlap between these specific point patterns of certain phenotypes in R that is overlapped with the image mask.
Attached is an image that I was able to segment in R, however how do I match the coordinate space from histoCAT with the raw image locally?   how does histoCAT operate to create a uniform coordinate annotation with the image mask, **and ** the raw images (or the objects themselves)?

![test](https://user-images.githubusercontent.com/5473099/46899126-83416880-ce44-11e8-87be-1ca2c6ec306a.png)

**Comment by arcolombo** [comment]
For example, if the coordinates of an object is (100,100),  how do I see this point in the context of the mask.TIFF that is included in the input?  for instance, what type of coordinate spaces are used as the reference? is the TIFF considered "european", "cartesian" style?   are the coordinate axes scaled?  
 The goal for me would be to identify an object, and then pull the image mask, and identify EXACTLY where this object is located in the mask.
Thank you you all very much,
AC

**Comment by DenisSch** [comment]
Dear AC,

The X and Y coordinates represent the centroid of the cellular mask. If you plot the X and Y position on the labeled mask (e.g. visualized as a matrix) the coordinates should give you the corresponding Cell-ID.

Does this address your question?

Best

Denis

**Comment by DenisSch** [comment]
I will close this issue for now, but I am happy to re-open anytime if necessary.
