### ISSUE TITLE
Phenograph is a bug, "can not find G.bin, G.tree, G.weights".  These files do exist in the custom gates folder!

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/histoCAT#15]
Hello, I am running phenograph, and has been working fine for some time now.   I am using matlab to run phenograph from histocat version 1.75.   The  custom_gates folder is located on C:\Users\Public\Myfolder directory.
  
When I run phenograph on a gated cluster, I receive an error that it does not find the "G.bin". however these G files are located in my custom gates directory.
![capture](https://user-images.githubusercontent.com/5473099/48874985-19a16c00-edab-11e8-9137-3e0faf9480fb.JPG)

I reinstalled histocat and got the same error.   
 thoughts?

below is the log.

MATLAB: max level is 3
MATLAB: importing level 1
C:\Users\Public\histoCAT-master\histoCAT\3rdParty\PhenoGraph\Louvain_d\hierarchy.exe C:\Users\Public\Ansell\Anthony_gates_V04\custom_gates_0\custom_gates_0\G.tree -l 1 > C:\Users\Public\Ansell\Anthony_gates_V04\custom_gates_0\custom_gates_0\G.tmp
MATLAB: importing level 2
C:\Users\Public\histoCAT-master\histoCAT\3rdParty\PhenoGraph\Louvain_d\hierarchy.exe C:\Users\Public\Ansell\Anthony_gates_V04\custom_gates_0\custom_gates_0\G.tree -l 2 > C:\Users\Public\Ansell\Anthony_gates_V04\custom_gates_0\custom_gates_0\G.tmp
MATLAB: importing level 3
C:\Users\Public\histoCAT-master\histoCAT\3rdParty\PhenoGraph\Louvain_d\hierarchy.exe C:\Users\Public\Ansell\Anthony_gates_V04\custom_gates_0\custom_gates_0\G.tree -l 3 > C:\Users\Public\Ansell\Anthony_gates_V04\custom_gates_0\custom_gates_0\G.tmp
Warning: File 'G.tmp' not found. 
> In LouvainfromBin_Windows>cleanup (line 109)
  In LouvainfromBin_Windows (line 82)
  In phenograph (line 70)
  In Run_Phenograph_Callback (line 33)
  In analyze_button_Callback (line 80)
  In gui_mainfcn (line 95)
  In histoCAT (line 42)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('analyze_button_Callback',hObject,eventdata,guidata(hObject)) 
Warning: File 'G.tree' not found. 
> In LouvainfromBin_Windows>cleanup (line 109)
  In LouvainfromBin_Windows (line 82)
  In phenograph (line 70)
  In Run_Phenograph_Callback (line 33)
  In analyze_button_Callback (line 80)
  In gui_mainfcn (line 95)
  In histoCAT (line 42)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('analyze_button_Callback',hObject,eventdata,guidata(hObject)) 
Warning: File 'G_graph.weights' not found. 
> In LouvainfromBin_Windows>cleanup (line 109)
  In LouvainfromBin_Windows (line 82)
  In phenograph (line 70)
  In Run_Phenograph_Callback (line 33)
  In analyze_button_Callback (line 80)
  In gui_mainfcn (line 95)
  In histoCAT (line 42)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('analyze_button_Callback',hObject,eventdata,guidata(hObject)) 
Warning: File 'G.bin' not found. 
> In LouvainfromBin_Windows>cleanup (line 109)
  In LouvainfromBin_Windows (line 82)
  In phenograph (line 70)
  In Run_Phenograph_Callback (line 33)
  In analyze_button_Callback (line 80)
  In gui_mainfcn (line 95)
  In histoCAT (line 42)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('analyze_button_Callback',hObject,eventdata,guidata(hObject)) 
Warning: File 'G_graph.bin' not found. 
> In LouvainfromBin_Windows>cleanup (line 109)
  In LouvainfromBin_Windows (line 82)
  In phenograph (line 70)
  In Run_Phenograph_Callback (line 33)
  In analyze_button_Callback (line 80)
  In gui_mainfcn (line 95)
  In histoCAT (line 42)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('analyze_button_Callback',hObject,eventdata,guidata(hObject)) 
assigning random number for current Phenograph
Index in position 2 exceeds array bounds (must not exceed 69).

Error in parse_Phenographclusters (line 137)
        idx_id =
        find(ismember(ClusterData_final(:,clusterdata_pheno),clusterIDs(id)));

Error in Run_Phenograph_Callback (line 47)
[ pheno_clusters ] = parse_Phenographclusters( sessionData,gates );

Error in analyze_button_Callback (line 80)
    Run_Phenograph_Callback;

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in histoCAT (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('analyze_button_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

>>

**Comment by arcolombo** [comment]
So the Phenograph experiences this error when I try to "sub-phenotype" a specific gate.   

For context:  when I phenograph across a set of data, I have a set of clusters.  In order to "sub-classify" a specific cluster, I re-run the tSNE formation on a manual gate which only selects objects which belong to this specific cluster.
 If I then run phenograph again using a selected set of markers, phenograph will hang.
  Note this is using ADMIN computer and using the matlab version. 

ANy suggestions will be helpful.

**Comment by DenisSch** [comment]
What is the error message?
Are you using the same custom_gates_0 folder?

I can not reproduce the error - it works fine for me on MacOS with version 1.75

**Comment by arcolombo** [comment]
yes I restarted and it worked.  this is officially closed.  thank you again Denis.   the computer just sort of hung up but works after a fresh install. 

Sincerely
AC
