### ISSUE TITLE
tSNE failed

### ISSUE THREAD

**Issue by mattbliss90** [BodenmillerGroup/histoCAT#16]
Hello,
I'm trying to run tSNE on 4 of my samples and am getting the following error message:

tSNE Failed: Common causes are\na) illegal histoCAT installation path - spaces in path.\nb) illegal histoCAT installtion path-no writing permissions in folder.\nc) perplexity too high caused by insufficient number of points

**Comment by DenisSch** [comment]
Hi!
1) How many cells are in your 4 samples and how many channels? (See point c in the error message)
2) Do you run histoCAT with admin rights? (See point b in the error message)

**Comment by mattbliss90** [comment]
1. My four ROIs have 35,011 total cells with 21 channels
2. I'm not sure what you mean by running histoCAT with admin rights. I downloaded the software onto my desktop on my work computer so I am the only who is using it.

**Comment by DenisSch** [comment]
What operating system are you using?

**Comment by mattbliss90** [comment]
I've tried on both Windows 7 and Mac OS High Sierra both the same error message

**Comment by DenisSch** [comment]
Do you get the error message also when you use the example dataset? Would you mind sharing your session with me, if this is a problem related to your data.

**Comment by DenisSch** [comment]
Thank you for the update! I assume it was:
(c) perplexity too high caused by insufficient number of points
