### ISSUE TITLE
the Install problem on macOS Mojave10.14

### ISSUE THREAD

**Issue by xiaott2335** [BodenmillerGroup/histoCAT#18]

**Comment by xiaott2335** [comment]
I downloaded histoCAT1.71-1.75 and try to install them on macOS Mojave10.14 respectively,then failed.I can not find the reason.Should I wait for the new version?

**Comment by lramsa1** [comment]
I am experiencing the same problem. First attempt caused my computer to crash. Second attempt the installer hangs with no error message.

**Comment by DenisSch** [comment]
I have not compiled a MacOS 10.14 version of histoCAT yet. I will do it for the next version.

As a workaround, you can use histoCAT directly through MATLAB from source.
