### ISSUE TITLE
Debian install error

### ISSUE THREAD

**Issue by fanli-gcb** [BodenmillerGroup/histoCAT#19]
Hi,

I'm trying to install the linux release and get this error message (on an Ubuntu system):
> sudo dpkg -i histoCAT_1.75.deb
dpkg-deb: error: 'histoCAT_1.75.deb' is not a debian format archive
dpkg: error processing archive histoCAT_1.75.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 histoCAT_1.75.deb

histoCAT_1.75.deb is the same file as histoCAT_1.75_Debian.install, just renamed.

What exactly is this file, if not a deb? 

Thanks!

**Comment by DenisSch** [comment]
I am not using debian / ubuntu regularly, but from what I remeber you need a tool called `gdebi` to install debian files on ubuntu. Does this work?

**Comment by DenisSch** [comment]
As a workaround, you can use histoCAT directly through MATLAB from source.

**Comment by DenisSch** [comment]
Do you still have the described issues? If yes, please reopen the issue.
