### ISSUE TITLE
Breast cancer data fcs files

### ISSUE THREAD

**Issue by sarahhcarl** [BodenmillerGroup/histoCAT#21]
Hi,

I would like to use your breast cancer example data, in particular to look at the fcs files after analysis with histoCAT, but I can't figure out which is/are the correct files.

In the downloads section, I found one file under the Data_52_BreastCancerSamples called sessionFCS.fcs, but this appears to only have 2 samples in it (2 unique image IDs). There is no corresponding file in the Data_6_NormalTissueSamples folder. I also downloaded the ResubmissionFullSession.fcs file, but when I try to load it in R using flowCore, I get the following error:

```
> full <- read.FCS("../ResubmissionFullSession.fcs", transformation = "none")
Error in readFCSgetPar(x, "$BYTEORD") : 
  Parameter(s) $BYTEORD not contained in 'x'
In addition: Warning messages:
1: Missing the required $BEGINDATA keyword! Reading data based on information in the FCS HEADER only. 
2: Missing the required $ENDDATA keyword! Reading data based on information in the FCS HEADER only. 
```

Am I missing something here? Thanks for the help!

Best,
Sarah

**Comment by DenisSch** [comment]
This is linked to #12 
Workaround is to export the data CSV for now.
