### ISSUE TITLE
99th percentile normalization question

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/histoCAT#24]
Hello.  this is a question about the 99th percentile normalization.  does the mynormalize.m  script normalize the 99th percentile relative to the case? or across all cases?  If I am analyzing a cohort,do I normalize the 99th percentile relative to each case, or percentile norm across the full data set (i.e. normalzing them together). 

thank you
AC

**Comment by DenisSch** [comment]
Dear AC,

The percentile normalization is performed on all selected samples. For example: If you select only 5 out of 10 samples it will be applied to the selected 5 samples.

Does this answer your question?

Best

Denis

**Comment by arcolombo** [comment]
Yes please close thank you

Voice transcribed from an iPhone v.6.
