### ISSUE TITLE
Question about the Export to CSV

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/histoCAT#25]
Hi .  question here,  when the user exports the histoCAT input files, are those the percentile normalized ? or the raw?   Essentially I exported the histoCAT data, and am not sure if I need to percentile normalize again for any future LOCAL analysis.

Thank you again,
AC

**Comment by DenisSch** [comment]
Please let me know if you have any further questions. If not, please let me know and I can close this issue.

**Comment by arcolombo** [comment]
thank you so much. yes please close.
