### ISSUE TITLE
Viewing a Full.tiff in histocat

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/histoCAT#26]
Hi.
So i am using imctools for CP3 and have compensated my images and output the object intensity excel sheet and the compensated FULL.TIFF (multistack tiff with all the channels).

However we want to view the full.tiff in histoca.  Is it possible to unstack the multistack full.tiff, and save the individual channel tiffs to upload into histocat?

Using python i can save each channel as its own tiff to “unstack” the FULL.tiff.  Can i then upload these in histoCAT from the “HISTOCAT” folder (which contains he mask)?

Will histoCat accept these if i manually unstack the multistack compensated FULL.tiff?

Thank you

**Comment by DenisSch** [comment]
Yes, if you have all tiff files as individual channels it should work! Please let me know if you encounter any problems.
