### ISSUE TITLE
exe file for bh_tsne_linux64

### ISSUE THREAD

**Issue by CNicholasMDA** [BodenmillerGroup/histoCAT#27]
Hi!
New user here.  Can you help me to download a copy of the executable file for bh_tsne_linux64?  For some reason, the file saved here downloads as a Text file, not an exe.  Am I missing something?
Thanks for your time!
-Courtney

**Comment by DenisSch** [comment]
Dear Courtney,
The file downloads as a .dms file. It is potentially interpreted by your operating system as a different file format. Please find the file attached.

I hope that answers your questions.

[bh_tsne_linux64.dms.zip](https://github.com/BodenmillerGroup/histoCAT/files/3015445/bh_tsne_linux64.dms.zip)

**Comment by CNicholasMDA** [comment]
You are most kind.  Thank you so much!
Best of luck with your work.
