### ISSUE TITLE
neighborhood analysis missing one cluster

### ISSUE THREAD

**Issue by dalide** [BodenmillerGroup/histoCAT#29]
Hi, 

I run the neighborhood analysis on one image, and it generates 10 phenograph clusters, but in the heatmap, there are 9 rows and 10 columns, which does not make sense to me. Please see the attachment.  
![heatmap_clusters_0p05](https://user-images.githubusercontent.com/16587569/58769293-44932680-856b-11e9-9275-444af77d83e7.jpg)

BTW I know Clustergrams will not be created if only one images selected, from this issue #8 ,  but I don't quite understand why not create the Clustergram, although it will be only one row.

**Comment by JanaFischer** [comment]
Hi,

when histoCAT generates this heatmap, rows/ columns that are empty (all white) get excluded automatically. Probably, there was no significant  interaction of cluster 10 with any of the clusters neighboring it in this image and therefore the row for cluster 10 would have been empty and got excluded.

Regarding the Clustergram, you are right one could also look at it for just a single row. The reason it is not output for only 1 image, is that the function generating the clustergram expects to hierarchically cluster the rows, which fails with only 1 row.

**Comment by dalide** [comment]
> Hi,
> 
> when histoCAT generates this heatmap, rows/ columns that are empty (all white) get excluded automatically. Probably, there was no significant interaction of cluster 10 with any of the clusters neighboring it in this image and therefore the row for cluster 10 would have been empty and got excluded.
> 
> Regarding the Clustergram, you are right one could also look at it for just a single row. The reason it is not output for only 1 image, is that the function generating the clustergram expects to hierarchically cluster the rows, which fails with only 1 row.

Thanks Jana. I think it is a reasonable explanation for the heatmap.
