### ISSUE TITLE
error loading images and tiff mask

### ISSUE THREAD

**Issue by SchulzDan** [BodenmillerGroup/histoCAT#3]
Warning: File: Load_mask.m Line: 163 Column: 5
This try-catch syntax will continue to work in R2007b, but may be illegal or may mean something different in future releases of MATLAB.
See MATLAB R2007a Release Notes, "Warning Generated by try-catch" for details. 
> In Load_MatrixDB at 29
  In Master_LoadSamples at 41
  In gui_mainfcn at 95
  In histoCAT at 42
  In @(hObject,eventdata)histoCAT('Master_LoadSamples',hObject,eventdata,guidata(hObject)) 
Error using iptassert (line 19)
Size of I doesn't match size information found in the first input argument.

Error in regionprops>ParseInputs (line 1168)
    iptassert(isequal(sizeImage,size(I)), ...

Error in regionprops (line 154)
[I,requestedStats,officialStats] = ParseInputs(imageSize, varargin{:});

Error in Process_SingleCell_Tiff_Mask>@(chan)struct2array(regionprops(Current_Mask,chandat{chan},'MeanIntensity'))' (line 74)
            get_mean = @(chan) struct2array(regionprops(Current_Mask, chandat{chan}, 'MeanIntensity'))';

Error in Process_SingleCell_Tiff_Mask (line 75)
            mean_tab = cell2mat(arrayfun(get_mean,1:length(chandat), 'UniformOutput',0));

Error in DataProcessing_Master (line 29)
    [Fcs_Interest_all] = Process_SingleCell_Tiff_Mask(Tiff_all,Tiff_name,Mask_all,Fcs_Interest_all,HashID);

Error in Master_LoadSamples (line 50)
[Fcs_Interest_all] = DataProcessing_Master(Mask_all,Tiff_all,Tiff_name,HashID,Fcs_Interest_all);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in histoCAT (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)histoCAT('Master_LoadSamples',hObject,eventdata,guidata(hObject))

 
Error while evaluating Menu Callback

**Comment by DenisSch** [comment]
Hi Daniel,

You received this error message because your mask is not the same size as the image. I consider this error as resolved after our last conversion.

Please do not hesitate to reopen the issue if it is not solved.

Best

Denis

**Comment by maxgrigori** [comment]
Hi Denis & Daniel, 

I have the exact same error showing up. Could You please post the solution to your problem here, as I cannot find your last conversation? That would be superb!

Best, Max

**Comment by DenisSch** [comment]
Can you check whether your mask and tif image are the same dimensions? E.g. open in Fiji/ImageJ to check dimensions

**Comment by maxgrigori** [comment]
Hi Denis, 

They do not seem to have the same dimensions. The mask images usually are 250x250 while the other tif images are larger. 
Is this causing the issue? And how could I try to fix it?

Thank You a lot for your hep!

best, Max

PS: I had also opened an issue before I stumbled upon this one.
It's this one here: https://github.com/BodenmillerGroup/histoCAT/issues/75
