### ISSUE TITLE
Setting random seed for Phenograph

### ISSUE THREAD

**Issue by SteveBoothHLI** [BodenmillerGroup/histoCAT#30]
Hi Dennis, thanks for implementing the set seed for reproducible clustering between runs.

Just testing this feature and I selected "yes" for set random seed, but I was not asked to specify or choose the seed number. Presumably when you select 'yes' the random seed is automatically set to the same number every time? What is the seed set to in this case?

Best,
Steve

**Comment by DenisSch** [comment]
Hi Steve,

We are using "2" as the random seed. If you would like to change the random seed, please follow the link to the code above.

Best

Denis
