### ISSUE TITLE
what is function changem? 

### ISSUE THREAD

**Issue by dalide** [BodenmillerGroup/histoCAT#32]
Hi I tried to export the csv, but it seems this is a typo in the file ExportCSV_singlecells.m at line 85, can you double check?  Thanks, here is the link to the location : https://github.com/BodenmillerGroup/histoCAT/blob/54c55b5e4866ea47f86e134fa1db5804c93fbd42/histoCAT/GUI/Save_button_options/ExportCSV_singlecells.m#L85

**Comment by DenisSch** [comment]
@dalide 
Can you give some more details on the error message? What is the typo?

Changem (https://ch.mathworks.com/help/map/ref/changem.html) is a MATLAB function.

**Comment by DenisSch** [comment]
I will close the issue - please feel free to reopen
