### ISSUE TITLE
why heatmap needs column normalization? 

### ISSUE THREAD

**Issue by dalide** [BodenmillerGroup/histoCAT#33]
Hi @DenisSch can you share the reason why the heatmap needs column normalization? 
 
I found that when I plot the heatmap using phenograph clusters and selected channels, the values shown in the heatmap is normalized between 0 and 1 using x-min(x)/max(x)-min(x).  But one problem I have is that for example, marker A have overall relatively low intensity for all the clusters, marker B have overall higher intensity, but after normalization by markers(i.e., columns in the heatmap), marker A will shows high values across the column while marker B have high value display in certain clusters. If in the heatmap, marker A and marker B both show high value in cluster 1, then I would think they both co-express, but in fact,  marker A is very low compared to marker B, if I don't normalize by column, the heatmap will show marker B in high value but see very little marker A, then I would not think they co-express. 

Thanks

**Comment by DenisSch** [comment]
Dear Dalide,

This is purely a visualization challenge. If the marker intensities are all similar, this is unnecessary step. However, if the markers have very different dynamic ranges this step is required for visualization.

Below an examples:

```
A = [1,2,3;1000,1004,1002]';

A =
 1        1000
 2        1004
 3        1002

imagesc(A(:,1:2))

```
![Non-normalized](https://user-images.githubusercontent.com/7010437/63195691-51d79180-c041-11e9-9cdf-45004b6abf77.jpg)

```
A(:,3) = (A(:,1) - min(A(:,1)))/(max(A(:,1))-min(A(:,1)));
A(:,4) = (A(:,2) - min(A(:,2)))/(max(A(:,2))-min(A(:,2)));

A(:,3:4)

ans =
0         0
0.5000    1.0000
1.0000    0.5000

imagesc(A(:,3:4))
```

![Normalized](https://user-images.githubusercontent.com/7010437/63195779-88ada780-c041-11e9-85a2-33c068370f24.jpg)

Does this address your question?

Best

Denis

**Comment by dalide** [comment]
Hi @DenisSch Thanks for the reply. I understand what you said, but what I mean is that like this:

```
A = [1,2,3;10,20,300]'
A =
     1    10
     2    20
     3   300
imagesc(A(:,1:2))
```
![pic1](https://user-images.githubusercontent.com/16587569/63199435-77659a80-c043-11e9-95ca-86e04bb91646.jpg)

```
A(:,3) = (A(:,1) - min(A(:,1)))/(max(A(:,1))-min(A(:,1)));
A(:,4) = (A(:,2) - min(A(:,2)))/(max(A(:,2))-min(A(:,2)));
A(:,3:4)

ans =

                   0                   0
   0.500000000000000   0.034482758620690
   1.000000000000000   1.000000000000000
```
![pic2](https://user-images.githubusercontent.com/16587569/63199501-a0862b00-c043-11e9-9562-d8af39c804f4.jpg)

in this case, after normalization, the last row both show yellow which leads me think they co-express, but the actually intensity level differ so much.  I certainly agree it is a standard way for visualization when two sets of data have very different dynamic ranges. So I wonder if my interpretation of the heatmap is right after the normalization, maybe I should just look at each marker individually?  

Thanks

**Comment by DenisSch** [comment]
Dear Dalide,

I don't know the details of your experiment, but from what I understand, I would use bi-axial scatter plots to visualize correlation (co-expression) instead of heat maps. If you are interested in co-expression of many different markers, I would suggest the PhenoGraph approach to identify clusters of similar cell identity.

Best

Denis

**Comment by DenisSch** [comment]
@smaffiol @votti Was there a change in group settings? I can't close issue anymore...?

**Comment by dalide** [comment]
> Dear Dalide,
> 
> I don't know the details of your experiment, but from what I understand, I would use bi-axial scatter plots to visualize correlation (co-expression) instead of heat maps. If you are interested in co-expression of many different markers, I would suggest the PhenoGraph approach to identify clusters of similar cell identity.
> 
> Best
> 
> Denis

Dear Denis, I see, Thanks for the suggestion!  I can close it.
