### ISSUE TITLE
Gating on plot 

### ISSUE THREAD

**Issue by jayp2919** [BodenmillerGroup/histoCAT#34]
Hello,

I am trying to gate on plot using histocat 1.76 Mac and Windows both but after I draw the gate I only hear a noise and no new sample for the custom gate. 
I tried on both computers and I am getting the same problem. 

I am not sure how to approach this 

Best
Jay

**Comment by DenisSch** [comment]
Dear Jay,

Do you have any spaces or special characters in the file name?
Does PhenoGraph work?

Best

Denis

**Comment by jayp2919** [comment]
Hello Denis,

Yes I found a space at the backend of one of the files and it is working now! 

Thank you 

Best

Jay
