### ISSUE TITLE
matlab error when loading samples

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/histoCAT#36]
Hello, I'm setting a new computer with the local matlab version and receiving an error when running the local matlab version of histoCAT.     The matlab return error is suggesting the naming of a particular channel is not a proper variable name.  However our panel has other markers with a hyphon.    The matlab manual suggests that variable names should be letters, digits, or underscores.  Does this mean the hyphon is not acceptable?

Also note if I use the pre-compiled version of histoCAT, the files load normally. 

MATLAB local run error: 
Error using table2dataset (line 12)
'Cell_Caspase-3Lu175Di_Lu175' is not a valid dataset variable name. Dataset variable names must be valid MATLAB identifiers, while
table variable names do not need to be. To make variable names valid before converting to dataset, use t.Properties.VariableNames =
matlab.lang.makeValidName(t.Properties.VariableNames).

**Comment by DenisSch** [comment]
The hyphen can be an issue with some MATLAB versions. If possible, I would not use hyphen in the variable name.

**Comment by arcolombo** [comment]
we resolved this issue by using the latest histoCAT version 1.76
