### ISSUE TITLE
Unable to load multiple ROI files into Histocat

### ISSUE THREAD

**Issue by HiranmayiR** [BodenmillerGroup/histoCAT#37]
Hello,

I'm trying to upload multiple ROI folders containing single image tiffs and the cells mask into Histocat. 

There are no spaces, hyphens or special characters in any of the folder/file names.

It seems to be able to upload a single ROI folder/files, but "crashes" on subsequent sample loads. I'm able to upload each ROI individually, but not together as one working session.

Please let me know what other information I can provide to help resolve this issue. Currently we are using histoCAT_1.71. We tried to uninstall the software and reinstall it, still no luck!

**Comment by arcolombo** [comment]
use histoCAT_1.76 the version does matter.

**Comment by arcolombo** [comment]
also make sure that your panel names match across all ROIs.   in my case I have seen if you panels do not match it will cause errors loading.

**Comment by DenisSch** [comment]
@HiranmayiR  Did any of the @arcolombo suggested help? Please let me know!

**Comment by HiranmayiR** [comment]
Hi All,

Yes, after changing the panel names to be identical in all the ROIs, we were able to upload all ROIs to HistoCAT. Thank you for your prompt response, yesterday!

Best,
Hiran
________________________________

**Comment by DenisSch** [comment]
Happy to hear - feel free to close the issue.
