### ISSUE TITLE
Loading ROIs that were ablated with non-matching panels

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/histoCAT#38]
Hello,
 so we have 5 experiments that were ablated using IMC.   3 of the experiments had matching panels.  2 of the experiments have markers that were not in the other 5.

I can load the 3 matching experiments simultaneously into histoCAT, however there are issues when I load the experiment without the matching panel.

When I create a new histoCAT folder where I ONLY INCLUDE THE MATCHING TIFFs and mask, the files do not load into histoCAT.   even when I try to 'trick' histoCAT, and delete TIFFs that are not  in all ROIs,  I can not load.

**Comment by DenisSch** [comment]
Are folder names unique? Are the marker names unique? What is the error message you see?

**Comment by DenisSch** [comment]
Is this still an open issue?

**Comment by arcolombo** [comment]
you can close.  please.

thank you very much Dennis.
