### ISSUE TITLE
macOS10.15 installation

### ISSUE THREAD

**Issue by DenisSch** [BodenmillerGroup/histoCAT#40]
Email Issue:

I'm reading the histoCAT installation guide as I'm failing to download histoCAT onto my macbook. It is stuck on the page attached without making any changes or looking as it does in the installation guide. 

Could it be because the computer is running macOS10.15 and that version is not yet supported? If so, do we know when we might get an upgraded version? 

Thanks, 

Tinaye 

<img width="437" alt="Screen Shot 2019-10-25 at 10 08 29 AM" src="https://user-images.githubusercontent.com/7010437/67590387-eab51800-f728-11e9-87d0-552682d89e32.png">

**Comment by DenisSch** [comment]
I will release a new version for macOS10.15. Anyone else experiencing the same issue?

**Comment by hegewisch15** [comment]
Also having this issue would appreciate the new version as I prefer using my MAC

**Comment by DenisSch** [comment]
I am aiming to release a new version in about a week.

**Comment by parkerpensmith** [comment]
Thank you so much for working on this!
All our MACs were updated and now we're stuck. We can't revert to 14 and don't have PCs :(

**Comment by hegewisch15** [comment]
Are there any updates on this? Sorry very excited to get back into my data analysis

**Comment by DenisSch** [comment]
@hegewisch15 @parkerpensmith I have (hardware related) issues to install macOS10.15, so I am waiting for a loaner to compile it. I will also reach out to @JanaFischer for help

**Comment by oclomas** [comment]
Agree with all above - any news of a 10.15 fix?

**Comment by hegewisch15** [comment]
Any update on this, anxiously waiting for some good news :)

**Comment by DenisSch** [comment]
Quick update that I am working on a compiled version for MacOS Catalina for the next big release.
In the meantime you can always run histoCAT through MATLAB directly. There is no bug - just no compiled version for macOS Catalina available yet.

**Comment by jdbs82** [comment]
Hi DenisSch,

Thanks for the suggestion. 
According to MATLAB, the only 10.15 compatible version is MATLAB R2019b.
Will histoCAT run on it?

Cheers

**Comment by DenisSch** [comment]
It should run on MATLAB 2019b, but we have not tested extensively. Please feel free to report any bug you find!

**Comment by gilly68g** [comment]
Hi There! Cool software!!! Thanks for your hard work and major contribution to helping others figure out what is going on in their images!! 

Here is an error message from Matlab 2020a (running old version until this is worked out)
>> histoCAT
Check for missing argument or incorrect argument data type in call to function 'put'.

Error in histoCAT>histoCAT_OpeningFcn (line 77)
put('loadflag',loadflag);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in histoCAT (line 42)
    gui_mainfcn(gui_State, varargin{:});

Cheers! Lane

**Comment by DenisSch** [comment]
I have managed to create histoCAT optimized for MacOS15 running on MATLAB2014b.
https://github.com/BodenmillerGroup/histoCAT/releases

**Comment by dingxm** [comment]
I downloaded the histoCAT_1.761_MacOS15.app.zip and tried to install in my MAC(MacOS15). I got below error:

 # A fatal error has been detected by the Java Runtime Environment:
#  SIGSEGV (0xb) at pc=0x000000010e32a400, pid=22112, tid=3587
# JRE version: Java(TM) SE Runtime Environment (7.0_55-b13) (build 1.7.0_55-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.55-b03 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libinstutil.dylib+0x9f400]  l_getid_type+0xded
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
Please help to take a look at the issue. Is it a java version issue?
