### ISSUE TITLE
neighborhood analysis phenotype heatmap row and column

### ISSUE THREAD

**Issue by dalide** [BodenmillerGroup/histoCAT#42]
Hi @DenisSch I have a question about the row and column in the phenotype heatmap from neighborhood analysis,  as the following picture, coming from the paper,

<img width="1003" alt="Screen Shot 2019-12-02 at 10 41 19 AM" src="https://user-images.githubusercontent.com/16587569/69977402-593b8180-14f0-11ea-86f4-6e52c813ee59.png">

say, **row 7 means is the cell type X from each column in the neighborhood of type 7**, 
but what I see in the code is the opposite, in the file "Calculate_STDandMean.m",

```
Find_cluster_in_neighbormatrix = find(combos_all(i,1)==Phenograph_Neighor_Matrix);
[row_cluster_matrix,~] = ind2sub(size(Phenograph_Neighor_Matrix),Find_cluster_in_neighbormatrix);
Find_Cluster_in_PhenoVector = find(combos_all(i,2)==Phenograph_Vector);
```

and in "Asymmetric_heatmap.m"

```
Sum_all_matrix_high(Clusters_to_exclude_high) = 0;
Sum_all_for_transformation_high = [Unique_high_all Sum_all_matrix_high'];

n = max(Sum_all_for_transformation_high(:, 1));
m = max(Sum_all_for_transformation_high(:, 2));
SymmetricHeatMap_high = nan(n, m);
for i = 1:length(Sum_all_for_transformation_high)
    SymmetricHeatMap_high(Sum_all_for_transformation_high(i, 1), Sum_all_for_transformation_high(i, 2)) ...
        =Sum_all_for_transformation_high(i, 3);
end
```

it looks like combos_all(:,2) is the phenotype in interest and combos_all(:,1) is the phenotype in neighborhood, and the code puts first column as the row and second column as the column in the heatmap, should it be interpreted as, **say for column 7, is the phenotype from each row in the neighborhood of type 7**? 
    
I got confused

thanks

**Comment by dalide** [comment]
@DenisSch Sorry to bother, I wonder if this issue will be answered in some time point. Thanks.

**Comment by DenisSch** [comment]
Dear Dalide,

I believe that (b) describes the graph the best:
Row: Cell type X in neighborhood of cell types of interest
Column: Cell type of interest in neighborhood of cell type x

I agree that combos_all(:,1) -> neighbors and combos_all(:,2) -> PhenoGraph, but that is not used for plotting in Asymmetric_heatmap.m

Important to mention: https://github.com/BodenmillerGroup/histoCAT/commit/de5f8ad28d689119ddfd196803e3d8264c3ae556 updated the neighborhood analysis in comparison to the publication, so the results may look slightly different.

**Comment by dalide** [comment]
@DenisSch thanks for your reply.  I am glad that I do understand correctly about combos_all(:,1) -> neighbors and combos_all(:,2) -> PhenoGraph. 

But in "Neighborhood_Master.m", 
```
parfor_gates_high(image_num) = {[combos_all,Higher_logic]}
```

then in "Heatmap_individual_images.m"
```
Higher_logic_gate_output = [Higher_logic_gate_output;index_for_image_high,parfor_gates_high{1,i}];
Unique_all = unique(Higher_logic_gate_output(:,[2 3]),'rows');
% Save unique combinations for heatmap names
Unique_high_all = unique(Higher_logic_gate_output(:,[2 3]),'rows');
```

then in "Asymmetric_heatmap.m"
```
Sum_all_for_transformation_high = [Unique_high_all Sum_all_matrix_high'];
SymmetricHeatMap_high = nan(n, m);
for i = 1:length(Sum_all_for_transformation_high)
    SymmetricHeatMap_high(Sum_all_for_transformation_high(i, 1), Sum_all_for_transformation_high(i, 2)) ...
        =Sum_all_for_transformation_high(i, 3);
end
```

it looks like combos_all pass to Unique_high_all, then to Sum_all_for_transformation_high, so Sum_all_for_transformation_high(:,1) is same as combos_all(:,1), Sum_all_for_transformation_high(:,2) is same as combos_all(:,2),  then plotting heatmap would have the same info from combos_all.

**Comment by DenisSch** [comment]
I will work through the code again and I will get back to you soon.

**Comment by DenisSch** [comment]
The upcoming next release will include a fix for this issue.
