### ISSUE TITLE
Percentile cut-off 

### ISSUE THREAD

**Issue by trnu20** [BodenmillerGroup/histoCAT#44]
Hello,

Can someone provide more information about using percentile cut-off when using Heatmaps in histoCat 1.76.

I am unsure how you are meant to determine the best cut-off point for each channel in 'Visualisation' with 0% and 100% giving the same output of all blue except one or 2 cells and with every other percentage giving a mass range of colours.

Also in 'Analysis' when generating a Heatmap of phenograph cluster gates with my selected channels, altering the cut-off doesn't affect the Heatmap at all. Shouldn't reducing the cutoff point increase the expression value for weaker expressed channels for each cluster?

Thanks in advance.

**Comment by DenisSch** [comment]
The default setting uses a cut-off for one 1 percentile (low and high). When the cut-off is changed it visualizes the data with a cut-off in percentage in the high values only.

I would suggest to use the default setting besides your values are dominated by outliers that are not removed by 1-percentile default setting.

**Comment by DenisSch** [comment]
Please let me know if you have any further questions. If this answered your question, please close this issue.

**Comment by trnu20** [comment]
@DenisSch thankyou for your help
