### ISSUE TITLE
takes too long to load the image

### ISSUE THREAD

**Issue by minhtran1309** [BodenmillerGroup/histoCAT#45]
I am using version 1.76 and trying to load my tiff images with size ~800x800, it takes me more than 1h to open the folders with two images inside. It doesn't seem to load as fast as the example images I download from the example folder. Does it have any problem with the memory ?

**Comment by DenisSch** [comment]
Would you mind sharing more information?
How many channels?
What are the specs of your system?

**Comment by minhtran1309** [comment]
Hi thank you for your response, 
1. The image is grayscale, I used the ImcSegmentationPipeline to produce the input image from .mcd all the way to .tiff files of a specific ROI. I tried to use a folder with only one image with (and without the mask in .tiff format also) but It could load it. 
2. I am using MacOs Mojave, 16Gb RAM, Intel I5.

**Comment by DenisSch** [comment]
Is the size of your mask and image the same? Is the tiff file 16bit integer?
If you don't mind, feel free to share an example file, so I can test it.

Alternatively, could you record the error message? To do so, please execute histoCAT directly through the terminal.

**Comment by DenisSch** [comment]
Please let me know if this issue is still open.

**Comment by minhtran1309** [comment]
Hi, I wasn't able to run the image through histocat. 
Some specs about our images. I generate each ROI fro MDviewer tool from the company provides (both 32bit and 16bit). I ran the pipelines from the other github through Ilastik and CellProfiler to generate mask. The data that I am using is confidential, I can't share it to you. 
I will log the post the error from terminal later today.

**Comment by DenisSch** [comment]
Is this still an issue?
