### ISSUE TITLE
Heatmap 

### ISSUE THREAD

**Issue by KLIV3R** [BodenmillerGroup/histoCAT#46]
I am trying to create a heatmap with my sample use only one region of interest however despite this the software will not produce this for me. Do i need to create a phenograph prior to this

KLIV3R

**Comment by SteveBoothHLI** [comment]
There are 2 ways you can utilize the heatmap in histoCAT and it depends on your question. Do you want to get the expression of the markers for the whole tissue/ROI. Or do you want to show the expression of markers for individual cell phenotypes? 

For a heatmap of cell phenotype specific marker expression: if you only have 1 sample or ROI you have to do the Phenograph first. Then select all the phenograph clusters from the sample list, then select the channels you want to display, and then make the heatmap. 

If you want to get a heatmap of the marker expression for the whole image/ROI this can also be done if you have multiple ROIs, just select the samples or gates and then the channels as described above.

Steve

**Comment by KLIV3R** [comment]
Steve,

Thank you very much for your help Steve, i am now able to create the heatmap.

KLIV3R
