### ISSUE TITLE
Histocat neighborhood anaysis

### ISSUE THREAD

**Issue by KLIV3R** [BodenmillerGroup/histoCAT#47]
I have successfully created a neighbourhood analysis and have the red and blue image. However i am now attempting to produce a clustergram and i am having difficulty doing this. Any help with this issue  is much appreciated.

KLIV3R

**Comment by DenisSch** [comment]
What exactly is the issue? If you are running neighborhood analysis on only one image no cluster gram will be created. Is this the case?

**Comment by trnu20** [comment]
Hi @DenisSch @KLIV3R I am experiencing a similar issue.

When running neighbourhood analysis on one image it doesn't generate the clustergram as expected however, when trying to run it with two images the first pop up window appears for amount of permutations, significant cut-off etc. Without changing any of these settings and clicking OK the pop up to select the phenograph(s) doesn't appear and there is no indication that it is running any analysis. 

I have followed the same steps for running neighbourhood analysis with only one image which has worked with the only difference in this case is selecting two images from the samples/populations column.

**Comment by trnu20** [comment]
@KLIV3R @DenisSch 

Turns out the neighbourhood analysis for multiple images only works if you have only ran one phenograph in the session window.

**Comment by DenisSch** [comment]
Yes, that is expected, since a common PhenoGraph is required for the neighborhood analysis.

A cluster gram can not be created for one image. See #8

**Comment by DenisSch** [comment]
If this does answer your issue, please close this issue.
