### ISSUE TITLE
Interpretation Neighbourhood Analysis and Phenograph Cluster

### ISSUE THREAD

**Issue by AnjaKolb** [BodenmillerGroup/histoCAT#48]
Hi,
I'm trying to figure out how I can use your program to perform neighbourhood analysis of my data. I have been able to analyse the data using the various options and following the manual. My problem is the analysis of the HistoCAT pictures. At the moment I´m not able to interpret the scatter plot of my tSNE overlapped with the phonograph or the heat map of the neighbourhood analysis. How can I identify which of my 22 different makers is in which Phenograph cluster? And how can I see which marker corresponds with which area on the scatter plot?

**Comment by DenisSch** [comment]
Dear Anja,

To visualize the markers expressed in the individual PhenoGraph clusters, please follow figure 15 in the manual. Therefore, select all PhenoGraph cluster, all markers of interest and then run "Heatmap". The result should be similar to figure 2c from the histoCAT paper.

Best

Denis

**Comment by DenisSch** [comment]
Please close this issue if it solves your question.

**Comment by AnjaKolb** [comment]
Is their any possibillity to export the basic data of the heatmap into an excel file  to make other statistic analysis with them?

**Comment by DenisSch** [comment]
Dear Anja,
You can export the CSV file with the corresponding cluster information by using the Save -> Export gates as CSV when selecting the PhenoGraph gates.

**Comment by DenisSch** [comment]
Does this answer your question?

**Comment by AnjaKolb** [comment]
yes thank you
