### ISSUE TITLE
The markers disappear when multiple images are selected

### ISSUE THREAD

**Issue by minghlijiyi** [BodenmillerGroup/histoCAT#49]
Hello,
All markers are showing in the channel list if I only selected one image, but when I selected multiple images, the markers disappear from the channel and heat map channel list. Could you help me? Thank you!
Best
Mingli

<img width="1680" alt="single image" src="https://user-images.githubusercontent.com/51270057/76709753-9ca0b100-66d7-11ea-9ecd-ca83b0b982b7.png">
<img width="1680" alt="multiple images" src="https://user-images.githubusercontent.com/51270057/76709756-a2969200-66d7-11ea-8dd1-2ca09ea3c663.png">

**Comment by DenisSch** [comment]
I will delete this issue. For the future, please keep issues open, so other users can learn from them.
