### ISSUE TITLE
Compiling Application for Distribution

### ISSUE THREAD

**Issue by hissingpanda** [BodenmillerGroup/histoCAT#50]
I've added a few custom features and am trying to use the Matlab 2014b Application Compiler to generate an exe installer for our lab. I'm able to do this and install successfully but once the application is open I'm not able to load any samples as the dialog box does not open upon selecting "Load Samples".

I'm wondering if I'm missing some of the project dependencies when I compile it? Or is there another step that I might be missing? These are the dependencies I select below.

![build](https://user-images.githubusercontent.com/7660115/77493205-b93b9800-6dff-11ea-8861-2f71ba2a5a2a.png)

**Comment by DenisSch** [comment]
I would put all files from histoCAT into the "Files required for your application to run" box. The automatic connection sometime fails, so this will make sure to include all files.

Let me know!

**Comment by hissingpanda** [comment]
This worked thank you!
