### ISSUE TITLE
Imageld

### ISSUE THREAD

**Issue by rcjm123** [BodenmillerGroup/histoCAT#53]
Hi, I'm relatively new to HistoCAT, I'm trying to import some IMC data (as ome.tiff files) and a segmentation mask I made in CellProfiler (as a .mat file). However, when I include the mask, the images don't open. The only channel that appears is 'Imageld'.

Is there something very obvious that I'm missing?

C

**Comment by DenisSch** [comment]
What is the name of your mask? Are you using "XXX_mask.mat"? If not try it.
Does the loading works without the mask?

**Comment by DenisSch** [comment]
Is this still an open issue?

**Comment by rcjm123** [comment]
Hello, sorry I was on annual leave over the Easter break. The mask is only listed as XXX.mat, I have renamed it in a XXX_mask.mat format and it still doesn't open

**Comment by Deltacell** [comment]
Hi Denis, 
I am having a similar problem - dataset with images open only when I remove the mask.tif image from the main folder. Using MATLAB2019 on MacOS Mojave. This is the error message on matlab:

>> histoCAT
Samples arranged..Loading Masks,Tiffs of all Samples..
Unrecognized function or variable 'struct2array'.

Error in
Process_SingleCell_Tiff_Mask>@(chan)struct2array(regionprops(Current_Mask,chandat{chan},'MeanIntensity'))' (line
86)
            get_mean = @(chan) struct2array(regionprops(Current_Mask, chandat{chan}, 'MeanIntensity'))';

Error in Process_SingleCell_Tiff_Mask (line 87)
            mean_tab = cell2mat(arrayfun(get_mean,1:length(chandat), 'UniformOutput',0));

Error in DataProcessing_Master (line 29)
    [Fcs_Interest_all] = Process_SingleCell_Tiff_Mask(Tiff_all,Tiff_name,Mask_all,Fcs_Interest_all,HashID);

Error in Master_LoadSamples (line 50)
[Fcs_Interest_all] = DataProcessing_Master(Mask_all,Tiff_all,Tiff_name,HashID,Fcs_Interest_all);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in histoCAT (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('Master_LoadSamples',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

Any idea what is going on? 

Cheers

**Comment by DenisSch** [comment]
`struct2array` seems to be missing in your MATLAB installation. You can add the following function to your path:

```
function a = struct2array(s)
%STRUCT2ARRAY Convert structure with doubles to an array.

%   Author(s): R. Losada
%   Copyright 1988-2013 The MathWorks, Inc.

narginchk(1,1);

% Convert structure to cell
c = struct2cell(s);

% Construct an array
a = [c{:}];```

**Comment by DenisSch** [comment]
Please reopen this thread if this remains an issue.

**Comment by rachel662** [comment]
Hi there, 
I'm having this issue and have tried to add this function in at the end of the script but for some reason it's not working? 
would you be able to help me with this at all? 
thanks 
Rachel

**Comment by rachel662** [comment]
I should add that I'm operating windows 10 but the script downloads histocat 1.76 which seems to be exclusively for mac? 
could this be why I'm getting these errors?
