### ISSUE TITLE
Histocat Web: Dataset Loading

### ISSUE THREAD

**Issue by cassandraman** [BodenmillerGroup/histoCAT#57]
Hi,
I've just started with the web version of Histocat, and I'm having trouble uploading my data. Under "Datasets" there isn't an option to upload, so I used "Slides," which only lets me select a single tiff image at a time. Afterwards, I get a message that says the upload was successful, but I don't see it added to the list and it's not searchable. 

Is there a way to upload multiple images of channels for multiple samples, and is there a way to see the slide after the upload?

Thanks, really appreciate your help!
Cassandra

**Comment by DenisSch** [comment]
Dear Cassandra,

@plankter is the best person to contact regarding the web version. Please let me know if this helps.

Best

Denis

**Comment by hissingpanda** [comment]
Where is the web version located?

**Comment by cassandraman** [comment]
Hi Denis,

Thanks for the reference!

@hissingpanda This link should work: http://130.60.24.98/login

**Comment by hissingpanda** [comment]
@cassandraman From messing around with it, it seems you can upload an MCD file and it will populate as a slide that's available for visualization. I don't know if there's a way to do it with tiff images and a mask however.

To use the analysis tab though it says it requires a dataset to be selected. I'm not sure how to curate a dataset or if that's not currently functional.

**Comment by hissingpanda** [comment]
@plankter are there plans to make the web version open source? It's very exciting and I would like to contribute.

**Comment by DenisSch** [comment]
This is the most updated information I have:
https://bodenmillergroup.github.io/histocat-web/

Feel free ask questions in the corresponding repository: https://github.com/BodenmillerGroup/histocat-web/
