### ISSUE TITLE
Origin of cells in phenograph clusters

### ISSUE THREAD

**Issue by HenrikeSalie** [BodenmillerGroup/histoCAT#58]
Hi,

I clustered the cells of my samples using the phenograph option in histocat and would now like to make sure that each cluster is composed of cells from many samples/images and not only one or two. Therefore it would be great to get information on where the cells in each cluster come from, i.e. to what percentage from which sample. Is there a way to obtain this information in histocat?

Best,
Henrike

**Comment by DenisSch** [comment]
Dear Henrike,

One quick way to check where the clusters are coming from is to plot PhenoGraph cluster number vs Image ID.
<img width="638" alt="Screen Shot 2020-07-17 at 5 12 09 PM" src="https://user-images.githubusercontent.com/7010437/87831196-c2d68900-c850-11ea-8001-a79f2672a49d.png">

Alternatively, if detailed analysis is required, you can always export the corresponding CSV which will provide an easy access to the underlying data (even with Excel).

**Comment by DenisSch** [comment]
Does this address your question?

**Comment by HenrikeSalie** [comment]
Dear Denis,

thank you for taking the time to answer my question.
Eventually we exported the CSVs of the PhenoGraph clusters and gated on the ImageID in FlowJo to receive frequencies.

Best,
Henrike
