### ISSUE TITLE
Loading in Files

### ISSUE THREAD

**Issue by hegewisch15** [BodenmillerGroup/histoCAT#60]
Hello, 

I was wondering if there was a limit to the file size that you can import into histocat. I am trying to upload multiple 1mmx1mm ROIs but it seems to fail every-time, although I can successfully upload two 1mmx1mm ROIs at a time so the limit seems to be about 2gbs. Even though I have a an 8 core  64 gb ram and 8 gb graphics card so in theory it should be able to handle more files. Is there a way to increase the amount of memory dedicated to histocat or to increase how many files I can load. 

Best,
Evey

**Comment by DenisSch** [comment]
Dear Evey,

What is the error message you are getting? Or does it just get stuck?

**Comment by hegewisch15** [comment]
It just stops loading and quits, I tried to upload different numbers of ROIs and re downloaded the software still I can only load two files.

**Comment by DenisSch** [comment]
Would you be able to run it via terminal/cmd so we can see the error message.
To run histoCAT in command line follow these steps:
https://www.wikihow.com/Run-Exe-from-Cmd-on-PC-or-Mac

**Comment by DenisSch** [comment]
@hegewisch15 Please let me know if this is still an issue.

**Comment by DenisSch** [comment]
Please reopen if still relevant!
