### ISSUE TITLE
Reproduce Neighborhood analysis Figure 3C

### ISSUE THREAD

**Issue by lp-kawai** [BodenmillerGroup/histoCAT#61]
Hello,
I am trying to reproduce the figure in Nature Methods.
I tried Neighborhood analysis and successfully reproduced Figure3D, however I'm not sure how I can create figure like Figure 3C.
Could you explain how I can create heatmap of Neighborhood analysis of phenotype clusters?
Thank you.

**Comment by DenisSch** [comment]
Clustergram and heat map should be created but potentially one will take longer than the other. Do you receive any error message?

**Comment by DenisSch** [comment]
Are you using your own data or the published data with the same parameters?

**Comment by lp-kawai** [comment]
@DenisSch Thank you for your reply. I am using the published data with the same parameters.
I am using histoCAT v1.74 on mac.
Data is histoCAT_sessionResubmission.mat
I read the paragraph "1. Neighborhood analysis" in manual and get the Figure 26 right figure. However no matter how long I wait, Figure 26 left figure (maybe something similar as Figure 3C in the paper?) did not come out.

**Comment by DenisSch** [comment]
@lp-kawai Would you be able to upgrade histoCAT to 1.76 and try again?
Do you get any error messages?
