### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by tinaappi** [BodenmillerGroup/histoCAT#7]
Hi,
I'm trying to figure out how your software works by using the 52 breast cancer sample data on your site to practice. I have been able to analyse the data using the various options and following the manual with the exception of phenograph and neighbourhood analysis. With regards to the phenograph, after selecting the channels and the images and then run phenograph, it gives me the please wait pop up and thats it. No output never comes out. And since i cannot generate the phenograph, am not able to run the neighbourhood analysis. Kindly help out, maybe am selecting channels or images that are not appropriate. I usually select all the images and the channel.

**Comment by DenisSch** [comment]
Was this solved?

**Comment by tinaappi** [comment]
Yes. Thank you.
