### ISSUE TITLE
issues about file loading in histoCAT_1.76

### ISSUE THREAD

**Issue by dojo8** [BodenmillerGroup/histoCAT#71]
Hello, 

I installed the histoCAT_1.76 version on my Mac and it is running. 
In case of loading in my folder containing my ome.tiff images as well as my cell mask I will asked for entering the pixel expansion as well as for data transformation. Upon entering 4x4 and "do not transform data" nothing will be loaded. 

Any idea how to solve it?

Thanks!

**Comment by maxgrigori** [comment]
Hello dojo8, 

Did you solve this issue? Because I have the exact same problem, both using histoCAT 1.76 & 1.73 and cannot seem to get past it...

I'd be super grateful for your help! 
Thank you and have a nice day, 
Max

**Comment by DenisSch** [comment]
What OS system are you using?
