### ISSUE TITLE
Phenograph clustering

### ISSUE THREAD

**Issue by arose20** [BodenmillerGroup/histoCAT#74]
Hi, is it possible to set the number of clusters generated when running phenograph clustering in histocat?

**Comment by DenisSch** [comment]
The amount of phonograph clusters can't be specified exactly, but it can be controlled. The smaller the "nearest neighbor" parameter the less clusters and vice versa:

<img width="170" alt="Screen Shot 2020-12-09 at 10 31 45 PM" src="https://user-images.githubusercontent.com/7010437/101718012-5ca40a00-3a6e-11eb-90f7-5d7255b5c4d9.png">

**Comment by arose20** [comment]
Great, thankyou for getting back to me.
