### ISSUE TITLE
Error in loading histocat-folder files & mask into histoCAT 1.7.3 (& 1.7.6)

### ISSUE THREAD

**Issue by maxgrigori** [BodenmillerGroup/histoCAT#75]
Hello, 

I have an error when trying to load my generated IMC-histocat-files from the BodenmillerGroupPipeline into histoCAT...
When I choose the directory and the folders I am then asked to define the pixels (which I leave on 4x4) and then to choose to transform the data, which I don't choose. 
After this nothing happens however. I am just getting a windows error sound and the left column stays empty...

Now I have tried to start histoCAT via the cmd. The error I am getting is:

C:\Program Files\BerndBodenmillerGroup\histoCAT\application>Samples arranged..Loading Masks,Tiffs of all Samples..
Warning: File: C:\Users\Maxim\AppData\Local\Temp\Maxim\mcrCache8.4\histoC0\histoCAT\Loading_New\Load_Functions\Load_mask.m Line: 162 Column: 5
This try-catch syntax will continue to work in R2007b, but may be illegal or may mean something different in future releases of MATLAB.
See MATLAB R2007a Release Notes, "Warning Generated by try-catch" for details.
> In Load_MatrixDB at 29
  In Master_LoadSamples at 41
  In gui_mainfcn at 95
  In histoCAT at 42
  In @(hObject,eventdata)histoCAT('Master_LoadSamples',hObject,eventdata,guidata(hObject))
Error using iptassert (line 19)
Size of I doesn't match size information found in the first input argument.

Error in regionprops>ParseInputs (line 1168)

Error in regionprops (line 154)

Error in Process_SingleCell_Tiff_Mask>@(chan)struct2array(regionprops(Current_Mask,chandat{chan},'MeanIntensity'))' (line 80)

Error in Process_SingleCell_Tiff_Mask (line 81)

Error in DataProcessing_Master (line 29)

Error in Master_LoadSamples (line 50)

Error in gui_mainfcn (line 95)

Error in histoCAT (line 42)

Error in @(hObject,eventdata)histoCAT('Master_LoadSamples',hObject,eventdata,guidata(hObject))

Error while evaluating Menu Callback

I am using Windows10, but have already tried both histoCAT 1.7.3 and 1.7.6 and it gives me the same error.

I would be very grateful for your help!!
Thank You and have a nice day!
Max

**Comment by DenisSch** [comment]
Dear Max,
It looks like your mask is mismatched with the image. Can you check the dimensions of the mask and the image? Are they identical?

**Comment by maxgrigori** [comment]
Hello Denis, 

Thank You for the quick reply! The _mask-images usually have a dimension of 250x250pixels while the other images are larger (e.g. one is 607x453 pixels large).
Is this causing the issue? And how can I make sure they are identical?

Thank You very much!
Best Max

**Comment by maxgrigori** [comment]
Hello,

Any solution this problem so far? I am really struggling to get behind why this mismatch in tiff-image-sizes occurs and how to fix the compatibility...

Thanks a bunch!
Best, Max

**Comment by DenisSch** [comment]
@maxgrigori I believe you are processing the cropped Ilastik images (which are only intended for training) instead of the the full image (607x453). Could you double check? The mask must be the same dimension as the image!

**Comment by maxgrigori** [comment]
Hi Denis, 
This was the issue! I hadn't noticed I was using those. Thank you very much!
Best, Max
