### ISSUE TITLE
Using histoCAT for cyclic immunofluorescence- image analysis

### ISSUE THREAD

**Issue by vinaya1990** [BodenmillerGroup/histoCAT#81]
I'm a PhD student working at Queen Mary University of London. I'm interested in profiling the microenvironment in colorectal cancer using cyclic immunofluorescence. Stained slides are scanned using a fluorescent microscope (Nanozoomer S60). I'm working on analysing these images with histocat.
I've uploaded a segmentation mask (exported from ilastik) and marker images for 4 fluorescent channels (including DAPI) to histocat (1000 by 1000 pixel image)
[histocat_example_8bit.xlsx](https://github.com/BodenmillerGroup/histoCAT/files/5855640/histocat_example_8bit.xlsx)
. Histocat is not identifying the cells in the mask as separate cells (it instead identifies 2 cells). I am wondering what the disconnect is due to. I’m using Windows histocat_1.75. My images are too big to attach here- please let me know if there's an email I can send them to?
Any help would be very much appreciated.
Thanks!
Vinaya

**Comment by DenisSch** [comment]
@vinaya1990 How many cells does your mask have? If more than 65535 (so 16bit) you will have to use 32bit for mask output. Is this the issue?

**Comment by vinaya1990** [comment]
Ah thanks for this- will try it out and get back in touch.
