### ISSUE TITLE
Does not finish with loading my files

### ISSUE THREAD

**Issue by daboe01** [BodenmillerGroup/histoCAT#82]
after opening my images (all in single folder, 16bit tiff, mask file included), histoCAT seems to hang indefinitely, no CPU load no movement in the progress bar.
any hint for getting around this? i am on windows 10, version 1.76

**Comment by DenisSch** [comment]
@daboe01 Does your folder structure has any spaces or special characters? If this is not the case, would you be able to run histoCAT via command line so we can see the error/warning messages?

**Comment by daboe01** [comment]
yes, that was the issue.
thank you!
