### ISSUE TITLE
Histocat++ Download

### ISSUE THREAD

**Issue by aagamboa** [BodenmillerGroup/histoCAT#83]
Do you know if the Histocat++ version still available for download? If so could you please help direct me to where I can find it? Thank you!

**Comment by SansMorel** [comment]
I think this might be the place to look: https://github.com/BodenmillerGroup/histoCAT3D/releases/tag/v2.0

**Comment by aagamboa** [comment]
The folder just contains plugins, but does not have the Histocat++ download.

**Comment by DenisSch** [comment]
Have you tried to contact @RaulCatena ?

**Comment by RaulCatena** [comment]
Thanks for redirecting Denis.
@aagamboa It turns out that the server for BodenmillerLab has changed and the link is broken.
I added the binaries to a release tag. Check it out here.
Let me know how it goes.
https://github.com/BodenmillerGroup/histoCAT3D/releases/tag/3.0

**Comment by DenisSch** [comment]
Thank you Raul! I will close this issue but please feel free to reopen if required.

**Comment by aagamboa** [comment]
The link works, thank you so much!!
