### ISSUE TITLE
Ways of providing single cell information/segmentation mask besides CellProfiler?

### ISSUE THREAD

**Issue by jasperblee** [BodenmillerGroup/histoCAT#84]
Hello,

I have developed a customized segmentation approach that generates a binary segmentation mask, and ImageJ ROIs as output. Is there a way of feeding this type of data into HistoCAT? I noticed that the example dataset used a CellProfiler segmentation mask, but we are not using this platform and I wanted to know if any other type of file could be read in. Thank you!

**Comment by DenisSch** [comment]
As long as the mask is a labeled mask (each pixel has either an object ID or zero for background), you should be able to directly load it into histoCAT. 
If your mask is binary, you could just create a labeled mask to enable loading into histoCAT.

**Comment by DenisSch** [comment]
@jasperblee Please let me know if you have any further question - just open this issue
