### ISSUE TITLE
Error in table2dataset 

### ISSUE THREAD

**Issue by rachel662** [BodenmillerGroup/histoCAT#87]
Hi there, 
I'm trying to load some data into histocat which i'm running through matlab and I get this error 
would anyone be able to advise me as to how I can fix this issue and place the relevant line of code in the right place? 

thanks so much 
Rachel 

`Error using table2dataset (line 12)
'Cell_Coll-III_Er166' is not a valid dataset variable name. Dataset variable names
must be valid MATLAB identifiers, while table variable names do not need to be. To
make variable names valid before converting to dataset, use
t.Properties.VariableNames = matlab.lang.makeValidName(t.Properties.VariableNames).

Error in store_sessionData (line 218)
                fcsdata = table2dataset(Fcs_Interest_all{hshidx,1});

Error in Master_LoadSamples (line 58)
store_sessionData(samplefolders,fcsfiles_path,Sample_Set_arranged,Fcs_Interest_all,HashID,Mask_all
);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in histoCAT (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('Master_LoadSamples',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

>> histoCAT
Samples arranged..Loading Masks,Tiffs of all Samples..
Elapsed time is 44.461880 seconds.
    {'C:\Users\Rache\Dropbox (The University of Manchester)\IMC Data\Test1\ImcSegmentationPipeline\Testrun\analysis\histocat\20-03-06 Tara Lung 4_s0_p4_r1_a1_ac'}
    {'C:\Users\Rache\Dropbox (The University of Manchester)\IMC Data\Test1\ImcSegmentationPipeline\Testrun\analysis\histocat\20-03-06 Tara Lung 4_s0_p4_r2_a2_ac'}
    {'C:\Users\Rache\Dropbox (The University of Manchester)\IMC Data\Test1\ImcSegmentationPipeline\Testrun\analysis\histocat\20-03-06 Tara Lung 4_s0_p4_r4_a4_ac'}
    {'C:\Users\Rache\Dropbox (The University of Manchester)\IMC Data\Test1\ImcSegmentationPipeline\Testrun\analysis\histocat\20-03-06 Tara Lung 4_s0_p4_r5_a5_ac'}

Files loaded: 2.47e-05sAllocated space for data: 0.0571364s
Error using table2dataset (line 12)
'Cell_Coll-III_Er166' is not a valid dataset variable name. Dataset variable names
must be valid MATLAB identifiers, while table variable names do not need to be. To
make variable names valid before converting to dataset, use
t.Properties.VariableNames = matlab.lang.makeValidName(t.Properties.VariableNames).

Error in store_sessionData (line 218)
                fcsdata = table2dataset(Fcs_Interest_all{hshidx,1});

Error in Master_LoadSamples (line 58)
store_sessionData(samplefolders,fcsfiles_path,Sample_Set_arranged,Fcs_Interest_all,HashID,Mask_all
);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in histoCAT (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)histoCAT('Master_LoadSamples',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.`

**Comment by DenisSch** [comment]
Please try to change the file names from ‘ Cell_Coll-III_Er166’ to ‘Cell_Coll_III_Er166’. Removing the minus should help to make it a matlab accepted variable name.

**Comment by DenisSch** [comment]
Did this work? If not, please reopen
