### ISSUE TITLE
Broken link: "52 Breast Cancer Samples" dataset unavailable

### ISSUE THREAD

**Issue by maltekuehl** [BodenmillerGroup/histoCAT#90]
Hi,

I would like to report that the link to the breast cancer example dataset that's included in the README is broken.
It currently points to [http://www.bodenmillerlab.org/histoCAT_downloads/Data_52_BreastCancerSamples.zip](http://www.bodenmillerlab.org/histoCAT_downloads/Data_52_BreastCancerSamples.zip), however the nginx server there responds with a 404 error. It seems that the lab web page was moved to the .com rather than the .org domain but that the link was not updated.

I would therefore like to ask whether the dataset is still available under a different link and suggest a change to the README.

Kind regards,
Malte

**Comment by DenisSch** [comment]
Thank you Malte. @bblab-git @plankter Could you repair the link?

**Comment by plankter** [comment]
@DenisSch I'll check who is managing the website. Do you know if the dataset is available somewhere else in case it is not on a new server?

**Comment by DenisSch** [comment]
@plankter Any updates on the breast cancer data set?

**Comment by DenisSch** [comment]
@JanaFischer @bblab-git @jwindhager Do you know what happened to the link on the website? Is the data still on the BB server?

**Comment by jwindhager** [comment]
I'm not involved in the lab homepage nor histocat maintenance, so wouldn't know. Maybe @malmstroem knows more? As @plankter asked before: where would the dataset be archived, so that it could be retrieved from there in case it isn't hosted on the homepage anymore?

**Comment by malmstroem** [comment]
The lab webpage was created by a private company; I don't know who is responsible for the content. I looked through some archives but could not find the requested dataset.

**Comment by JanaFischer** [comment]
We have changed the website a year ago and do not keep data on it anymore. @DenisSch I can send you the downloads that were on the old website and you can host it on Zenodo or where ever you prefer.

**Comment by DenisSch** [comment]
@JanaFischer That is great - thank you! I will push it to Zonodo and update here!
