### ISSUE TITLE
Urgent: HistoCAT can't open saved file using "load session data"

### ISSUE THREAD

**Issue by CharlesXXYY** [BodenmillerGroup/histoCAT#93]
After successfully loading my samples and successfully saving them, I can not reopen it using "load session data". 
When loading data, HistoCAT displays error: 

Error using load
Unknown text on line number 1 of ASCII file C:\Users\xizha\Desktop\A.mat
"".
Error in importdata (line 206)
Error in Load_sessionData (line 36)
Error in gui_mainfcn (line 95)
Error in histoCAT (line 42)
Error in @(hObject,eventdata)histoCAT('Load_sessionData',hObject,eventdata,guidata(hObject))
Error while evaluating Menu Callback

Thanks,

Charley

**Comment by DenisSch** [comment]
It looks like something is wrong with the ".mat" file. Would you be able to share the ".mat" so I can check what went wrong?

**Comment by DenisSch** [comment]
@CharlesXXYY Please open if this is still relevant!
