### ISSUE TITLE
Problem when running t-SNE

### ISSUE THREAD

**Issue by Claire-WenyueZhao** [BodenmillerGroup/histoCAT#94]
Dear,

When I started to run t-SNE, it showed a popup window and didn't progress. Is there something wrong with my operation or what can I do in order to process? I didn't understand what does this promotion means.

![03](https://user-images.githubusercontent.com/86836942/124277554-bccbdc00-db77-11eb-9fad-9327626fd0ec.JPG)

**Comment by DenisSch** [comment]
@Claire-WenyueZhao Did it finish at some point? Unfortunately, the bar often fails to display the progress but the command still runs normal.
