### ISSUE TITLE
Histocat crashes when trying to run TSNE

### ISSUE THREAD

**Issue by mattsmithuk** [BodenmillerGroup/histoCAT#95]
When I try to run a TSNE plot on my data, histoCAT crashes shortly after displaying the progress bar.

This behaviour is only seen on my desktop PC, it runs fine (but slowly) on my laptop.

When running from the command line I get the following output:

`Warning: The input to STR2FUNC "/?" is not a valid function name. This will generate an error in a future release.`
`> In histoCAT at 36`
`Normalizing according to the 99th percentile...`

I have tried releases 1.76 and 1.75, and have tried reinstalling
I have also tried running in Windows 7 and 8 compatibility modes

Current system spec:
- Windows 10 Professional (update)
- AMD Ryzen 7 3700X
- 32GB RAM
- NVIDIA GeForce GTX 1660 Super

**Comment by DenisSch** [comment]
@mattsmithuk Are you using any special characters (including "/", "-" or spaces) in the folder or file name?

**Comment by mattsmithuk** [comment]
No. I've also just tried moving the files into a directory on the root of the C: drive to reduce the path length and have the same problem

**Comment by DenisSch** [comment]
@mattsmithuk What if you just wait for the tSNE to finish, since the "error" message you shared is actually only a warning. Does histoCAT crash right afterwards or just does not move forward?

**Comment by mattsmithuk** [comment]
Histocat crashes almost immediately after the loading bar appears

**Comment by DenisSch** [comment]
Would you be able to share the session so I can reproduce the error? Did you try to run it on the exemplar data: https://github.com/BodenmillerGroup/histoCAT/releases/download/histoCAT_1.76/Example_Images.zip

**Comment by DenisSch** [comment]
Is this still an issue?
