### ISSUE TITLE
Unable to load large ROIs

### ISSUE THREAD

**Issue by danfuruan** [BodenmillerGroup/histoCAT#96]
I am trying to load files in release 1.73 on a Windows 10 but this process gets stalled at the stage with the pop-up "Loading all files from Database. This may take a while...". When I try this with a 1MB folder containing the mask, TIFFs, and summary.txt for an ROI with ~40 markers, this process takes a matter of seconds. However, when I try to load any ROI with a folder size 50MB-170MB, it stalls at the loading step for 24+ hours without progress. How can I get these files to load?

Thank you for the help!

**Comment by DenisSch** [comment]
@danfuruan Any updates on this issue? If not, please close this issue.
